pull_request_title: 'feat: new translations'
pull_request_labels:
  - translations
commit_message: 'feat: new translations for %language%'
append_commit_message: false
files:
  - source: /docs/src/en/**/*.md
    translation: /docs/src/%two_letters_code%/**/%original_file_name%
  - source: /docs/locales/en.json
    translation: /docs/locales/%two_letters_code%.json
